# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: lorisleiva/laravel-docker:7.3
    steps:
      - run: checkout
      - run: ls
      - run: composer clearcache 
      - run: composer create-project --prefer-dist laravel/laravel blog
      - run: ls blog
      - run: cp -r src blog/Vendor/laravel-pt-BR-localization
      - run: cd blog && php artisan vendor:publish --tag=laravel-pt-br-localization
      - run: "[ -f blog/resources/lang/pt-BR.json ]"
      - run: "[ -f blog/resources/lang/pt-BR/auth.php ]"
      - run: "[ -f blog/resources/lang/pt-BR/pagination.php ]"
      - run: "[ -f blog/resources/lang/pt-BR/passwords.php ]"
      - run: "[ -f blog/resources/lang/pt-BR/validation.php ]"
      